apiVersion: apps/v1
kind: Deployment
metadata:
  name: kserve-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kserve-model
  template:
    metadata:
      labels:
        app: kserve-model
    spec:
      containers:
      - name: kserve-model
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
