#FROM python:3.9-slim
#WORKDIR /app
#COPY pyproject.toml  ./
#RUN pip install poetry && poetry install --no-dev
#FROM python:3.9-slim
#WORKDIR /app
#COPY --from=builder /app /app
#CMD ["python", "api-gateway.py"]

FROM python:3.9-slim

WORKDIR /app

RUN pip install --no-cache-dir fastapi uvicorn


COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
