apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Rafathzami/Devops-Assignment.git'  
    targetRevision: HEAD
    path: Application/fast_api
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
