apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kserve-model-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Rafathzami/Devops-Assignment.git' 
    targetRevision: HEAD
    path: Application/kserve_server
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
